### ISSUE TITLE
usage with bun

### ISSUE THREAD

**Issue by dg14** [ppetzold/nestjs-paginate#1022]
if i use bun instead of nodejs, when i declare in the controller a get like that :
` @Get()
  findAll(@Paginate() query): Promise<Paginated<Workspace>> {
    return this.workspaceService.findAll(query);
  }
`
i must not specify query type PaginateQuery because:

`
SyntaxError: Export named 'PaginateQuery' not found in module .. /node_modules/nestjs-paginate/lib/index.js
`

bun version: 1.1.33
@nestjs/core: ^10.4.6
nestjs-paginate: "^9.3.0"

**Comment by Helveg** [comment]
what does your import statement look like? Unfortunately I don't think any of the developers have experience with Bun's module resolution. We'd probably need someone with Bun experience to take a look at our package and help us find out what we could do to solve your problem.

You could probably try tweaking your import statement to see if it helps. I suspect perhaps simply `import { PaginateQuery } from 'nestjs-paginate';` is your best bet?

**Comment by dg14** [comment]
> You could probably try tweaking your import statement to see if it helps. I suspect perhaps simply `import { PaginateQuery } from 'nestjs-paginate';` is your best bet?

I think it's not a problem in bun module resolution, but probably a issue of when it's resolved.

if i disable in module the inclusion of Controller but leave the service (in which the PaginateQuery is included and loaded correctly) it starts without the problem (also loading the service as injection on another active controller).

so i think the problem is when nestjs loads dependencies.
i don't know logic of controller discovery and resolution but i think is different.

the hack is not to use PaginateQuery in controllers, but is only an hack.

regards.

**Comment by Helveg** [comment]
Yea so since nothing of this happens in NodeJS I think it's Bun specific, and we'd need someone with Bun expertise to tell us whether this is a Bun bug, or whether there is something `nestjs-paginate` can do that addresses this in a way that does not cause any breaking changes for NodeJS users.

Please feel free to reopen this when you have found a suitable person with Bun experience to take a look at this. Without it there is nothing we can do for you. Sorry!
