### ISSUE TITLE
Unable to filter on values that contain a colon.

### ISSUE THREAD

**Issue by AlexStansfield** [ppetzold/nestjs-paginate#117]
I have some table IDs that contain colons as they are made up of two things concatenated together. I was trying to filter on this value and found the results just returned everything. I took a look and found it's likely to do with the way the filter value is split up.

https://github.com/ppetzold/nestjs-paginate/blob/85f60194ebf82871ebba23eff10c0a736882328f/src/paginate.ts#L178

Is there any way to make this work or should I be ditching the colon and using another separator whilst I still have the chance?

**Comment by ppetzold** [comment]
There is definitely a way to make it work - that's why I prefixed the operators with `$` to create a more unbiased pattern.

`/(\$\w+):/` something like this should work.


Just to recap the intended filter syntax:

**Equals:**
`filter.foo=bar` equivalent to `filter.foo=$eq:bar`

**Negation:**
`filter.foo=$not:bar` equivalent to `filter.foo=$eq:$not:bar` 

Writing `$eq` operator should be optional. But the above shows the max number of symbols in a filter query. 

Op1 + Op2 + Value

If you want to give it a try, you are welcome :) Otherwise I may have time later in the week to look into it.

**Comment by ppetzold** [comment]
Ah sorry, bad example: not sure if typeorm actually allows `Equal(Not('bar'))` - probably `Not(Equal('bar'))` would be more accurate.

But one of the test covers `$not:$in:1,2,5` which shows the syntax (Op1 + Op2 + Value) in full.

**Comment by AlexStansfield** [comment]
Thanks, for now I've actually change the `:` to a `|` in the IDs. Luckily can still do this whilst in development. Would much prefer to go back to `:` before we move to production in the next few days. If I get a chance I'll take a look at if I can make what you suggested work.

**Comment by AlexStansfield** [comment]
On deployment to AWS I found that API Gateway of course doesn't support `|` in the query string. So back to finding a character to use between the two strings I'm concatenating. If I get time I'll see if I can make the `:` work in the filter as that is my preferred choice.

**Comment by AlexStansfield** [comment]
I tried that regex you suggested but it introduced extra empty strings to the array.

So what I've done is split some of the code into smaller functions which I've then added unit tests. The unit test for `getFilterTokens` function has two failing tests where there are `:` in the string. 

The PR is #120, perhaps you can find a regex that'll make them pass. So far I've had no luck.
