### ISSUE TITLE
No proper documentation on filter usage for boolean fields

### ISSUE THREAD

**Issue by andrewhamili** [ppetzold/nestjs-paginate#988]
![image](https://github.com/user-attachments/assets/d2c7d62d-3e97-4ccb-bc32-37d77fd84202)             
 ![image](https://github.com/user-attachments/assets/d2c7d62d-3e97-4ccb-bc32-37d77fd84202)
![image](https://github.com/user-attachments/assets/5c24bc38-a077-4dc9-95d4-c21dc35cb4ac)

I was implementing a filter for boolean but the above code does not work as expected.

![image](https://github.com/user-attachments/assets/93a5fc6a-599f-495c-afc0-fe8531da1c07)
![image](https://github.com/user-attachments/assets/600a38a0-0115-46df-adb3-eb2be47d8eb9)

_Originally posted by @andrewhamili in https://github.com/ppetzold/nestjs-paginate/issues/339#issuecomment-2365400269_

**Comment by Helveg** [comment]
Hi, thanks for your report! 

Could you please post the full command and entirety of the output (build logs, error logs, ...) as pure text [formatted code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)? People with vision impairment, or other people who use screen readers will not always be able to interpret the image content.

Booleans should work if you use `0` and `1`. @ppetzold what about introducing `$true` and `$false` as operators, similar to `$null`? Otherwise it might be complicated to differentiate between `"true"` and `true`.

**Comment by Helveg** [comment]
Closing in favor of https://github.com/ppetzold/nestjs-paginate/issues/988
